server:
  port: 10003
  servlet:
    context-path: /user #根路径

spring:
  application:
    name: eureka-client-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root123456

# 打印 mysql 日志
logging:
  level:
    cn.lifecode.user.mapper: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/