server:
  port: 4591
  servlet:
    context-path: /music #根路径

spring:
  application:
    name: eureka-client-music
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/music
    username: root
    password: root123456

logging:
  level:
    cn.lifecode.music: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4590/eureka/